-- CreateTable
CREATE TABLE "PostItem" (
  "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  "postId" INTEGER NOT NULL,
  "title" TEXT NOT NULL,
  "description" TEXT NOT NULL,
  "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" DATETIME NOT NULL,
  CONSTRAINT "PostItem_postId_fkey" FOREIGN KEY ("postId") REFERENCES "Post" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "PostItemImage" (
  "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  "postItemId" INTEGER NOT NULL,
  "url" TEXT NOT NULL,
  "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "PostItemImage_postItemId_fkey" FOREIGN KEY ("postItemId") REFERENCES "PostItem" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);

